spring:
  application:
    name: javadoc-mcp-server
  ai:
    mcp:
      server:
        name: ${spring.application.name}
        capabilities:
          completion: false
          prompt: false
          resource: false
        type: async
        version: ${spring.application.version}