version: "3.8"

services:
  open-web-search:
#    image: registry.cn-hangzhou.aliyuncs.com/aasee-share/open-web-search:latest # 国内
    image: ghcr.io/aas-ee/open-web-search:latest
    container_name: open-web-search
    working_dir: /app
    restart: unless-stopped
    ports:
      - "15001:3000"
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    environment:
      NODE_ENV: production
      # DEFAULT_SEARCH_ENGINE: "duckduckgo" # Optional: 'bing' | 'duckduckgo' | 'exa' | 'brave', default bing (optional)
      # USE_PROXY: true # Using a proxy (optional)
      # PROXY_URL: "http://host.docker.internal:7890"  #  Using a proxy (optional)
      ENABLE_CORS: "true"
      CORS_ORIGIN: "*"  # Multiple values can be separated by commas and parsed accordingly | 可以多个值逗号分隔，自行解析
    command: ["node", "build/index.js"]
